Add heart box design
ascii-boxes/boxes pull request #99
Opened 2022-04-20 00:09 UTC by amychurchwell

Hi there! This is a box design I created from some text art I found on https://cutekaomoji.com a few years back. I've been using it in my .zshrc file locally and thought it might be a worthy contribution.

```
# ┌────────────── ∘°∘♡∘°∘ ──────────────┐
#              File: .zshrc
#
#   Used for setting interactive shell 
#   configuration and executing commands
#   for all users, will be read when
#   starting as an interactive shell.
#
# └────────────── °∘∘♡∘∘° ──────────────┘
````

Unfortunately, I struggled building this project and have not been able to test the design. I'm on MacOS and tried to use homebrew to install the dependencies on https://boxes.thomasjensen.com/build.html#unix, but continue to run into `make` problems that I can't really make sense of 🧐 ...

```
| For compilation info please refer to the boxes compilation FAQ
| at https://boxes.thomasjensen.com/faq.html#q5
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src BOXES_PLATFORM=unix LEX=flex YACC=bison build
echo parser.o lex.yy.o cmdline.o discovery.o generate.o input.o list.o parsecode.o parsing.o query.o regulex.o remove.o shape.o tools.o unicode.o > ../out/modules.txt
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../out -f ../src/Makefile BOXES_PLATFORM=unix ALL_OBJ="parser.o lex.yy.o boxes.o cmdline.o discovery.o generate.o input.o list.o parsecode.o parsing.o query.o regulex.o remove.o shape.o tools.o unicode.o" STRIP=true \
	    CFLAGS_ADDTL="-O " flags_unix boxes
echo parser.o lex.yy.o cmdline.o discovery.o generate.o input.o list.o parsecode.o parsing.o query.o regulex.o remove.o shape.o tools.o unicode.o > ../out/modules.txt
bison --warnings=all --verbose --defines=parser.h --output=parser.c ../src/parser.y
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison: unrecognized option `--warnings=all'
Try `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison --help' for more information.
make[2]: *** [parser.c] Error 1
make[1]: *** [build] Error 2
make: *** [build] Error 2
```

So hopefully this design is coded correctly, apologies if not.

2022-04-22 09:05 UTC, tsjensen commented
Thank you for sharing this cute box design!

Unfortunately, since it's not ASCII, we can't use it at the moment, until #72 is implemented. But we'll keep it around so we can add it once MBCS designs are supported.

If you have trouble building *boxes*, consider opening a separate issue for that. Mac is one of the frequently used platforms, so it should be fairly straightforward to get a working copy of *boxes* on your Mac. (Then again, I don't have access to a Mac myself, but maybe we can get someone else to help you.)

2025-05-28 11:44 UTC, tsjensen commented
Just found this again! Boxes supports UTF-8 config files in the meantime, so we can now adopt this box design, if you are still interested in contributing it.

2025-05-28 11:54 UTC, tsjensen requested changes
I added a number of comments with requests for small changes according to our [design best practices](https://boxes.thomasjensen.com/config-best-practices.html). I really like it! 👍

2025-05-28 11:54 UTC, tsjensen commented on boxes-config
> +
Could you add some sample box content here, like in your PR description?

2025-05-28 11:54 UTC, tsjensen commented on boxes-config
> +    nw ("┌─")
Please make this narrower, without the horizontal line, which will be added by the NNW shape.

2025-05-28 11:54 UTC, tsjensen commented on boxes-config
> +    ne ("─┐")
Please make this narrower, without the horizontal line, which will be added by the NNE shape.

2025-05-28 11:54 UTC, tsjensen commented on boxes-config
> +    vertical 3
```suggestion
    vertical 1
```
A little less padding seems right, wdyt?

2025-05-28 11:54 UTC, tsjensen commented on boxes-config
> +tags     "simple, box"
```suggestion
tags     ("unicode")
```
I think `unicode` is the only fitting tag in this case. Also, the `tag` syntax has slightly changed since last time. 🙂

2025-05-28 11:54 UTC, tsjensen commented on boxes-config
> +┌────────────── ∘°∘♡∘°∘ ──────────────┐
Please indent the sample by exactly 4 spaces.

2025-06-06 12:15 UTC, tsjensen commented
/ping @amychurchwell

2025-06-09 15:32 UTC, amychurchwell commented
hi there! thanks for the feedback. I should be able to find time to fix this up later this week. :)

2025-06-16 15:21 UTC, amychurchwell commented
Hi there, just circling back, I don't think I have time to work on this any time soon. Feel free to commandeer this change if you'd like to see it landed in the near future. Apologies. 😓

2025-06-20 12:16 UTC, tsjensen commented
No worries! Then I'll just close it again, and you can come back to it and reopen when you have time.

2025-06-20 12:16 UTC, closed without merging